language: python
python:
  - "3.7"
# command to install dependencies
install:
    - "pip install nose"
    - "pip install -r requirements.txt"
    - "python setup.py install"
# command to run tests
script: "nosetests -s -v"
