#!/bin/bash
#
#       /etc/rc.d/init.d/cb-yara-connector
#
. /etc/init.d/functions

prog="cb-yara-connector"
piddir="/run/cb/integrations/$prog"
pidfile="$piddir/$prog.pid"
logdir="/var/log/cb/integrations/$prog"
logfile="/$prog.startup.log"

command="/usr/share/cb/integrations/cb-yara-connector/yaraconnector --pid-file $pidfile --working-dir /usr/share/cb/integrations/cb-yara-connector --config-file /etc/cb/integrations/cb-yara-connector/yaraconnector.conf --daemon --log-file $logdir/cb-yara-connector.log --output-file /var/cb/data/cb-yara-connector/feed.json"

start() {
    if [ -f "$pidfile" ] && kill -0 $(cat "$pidfile"); then
        echo "Already started"
        return 1
    fi

    mkdir -p $piddir
    echo -n "Starting $prog: "
    $command &> $logfile
    result=$?

    if [ -f "$pidfile" ]; then
        echo "Ok"
    else
        echo "Failed"
    fi
    return $result
}

stop() {
    echo -n "Shutting down $prog: "
    if [ ! -f "$pidfile" ] || ! kill -0 $(cat "$pidfile"); then
        echo "Ok"
        return 1
    fi
	kill -s SIGTERM $(cat $pidfile) && rm -f $pidfile
	echo "Ok"
    return 0
}

status() {
    echo -n "Status of $prog: "
    if [ -f "$pidfile" ] && kill -0 $(cat "$pidfile"); then
        echo "Running"
    else
        echo "Stopped"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
esac
exit $?
