#!/usr/bin/env bash

git remote set-url --add --push origin git@gitlab.bit9.local:carbonblack/integrations/yara-connector
git remote set-url --add --push origin git@github.com:carbonblack/cb-yara-connector.git
git remote set-url origin git@gitlab.bit9.local:carbonblack/integrations/yara-connector.git
git remote -v
