#!/bin/sh
#
# cb-yara-bridge
#
# chkconfig:   2345 55 25
# description: The Carbon Black Yara Bridge is a Carbon Black component \
#              that integrates with Yara to provide \
#              a Carbon Black feed of Yara hits against binaries run in your environment.

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/share/cb/integrations/yara/cb-yara-connector"
prog="cb-yara-connector"
pidfile="/var/run/cb/integrations/yara.pid"

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5

    echo -n $"Starting $prog: "
    $exec start
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    [ -x $exec ] || exit 5

    echo -n $"Stopping $prog: "
    $exec stop
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    [ -x $exec ] || exit 5

    echo -n $"Restarting $prog: "
    $exec restart
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
